server:
  port: 8080

spring:
  application:
    name: idus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idus?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.example: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
